// Name, Keyword, Level, Description, Acquisition, Rules, Sticks, Stones, String, Scrap, Supplies


const CRAFTED_SCHEMES = [
  ["Disappearing Handkerchief Trick", "Deception", "2", '"Where\'d it go?"', "Crafted", null, "0", "0", "3", "0", "0"],
  ["Hole Covered With Leaves", "Deception", "1", null, "Crafted", null, "4", "0", "0", "0", "0"],
  ["Fake Jordans", "Manoeuvre", "3", null, "Crafted", null, "3", "0", "2", "0", "0"],
  [
    "Bommy Knocker",
    "Might",
    "4",
    '"I\'ll hit you with my Bommy Knocker - Mr Bommy Knockers Mans"',
    "Crafted",
    null,
    "1",
    "3",
    "3",
    "0",
    "0",
  ],
  ["A Rock Painted To Look Like A Grenade", "Deception", "3", "Look out!", "Crafted", null, "0", "1", "0", "0", "1"],
  [
    "Wearing Drag In An Attempt At Seduction",
    "Deception",
    "4",
    null,
    "Crafted",
    "If played against an Enemy with Horny in its name, the Enemy is immediately defeated.",
    "0",
    "2",
    "1",
    "0",
    "1",
  ],
  [
    "Sturdy Axe",
    "Might",
    "2",
    null,
    "Crafted",
    "If played whilst on a tile that grants sticks, you gain +1 stick",
    "1",
    "2",
    "2",
    "0",
    "0",
  ],
  ["University Degree", "Wit", "3", "I finally get to use this.", "Crafted", null, "0", "0", "1", "0", "1"],
  ["Makeshift Clown Disguise", "Sneak", "3", "I will blend in by sticking out.", "Crafted", null, "0", "1", "2", "0", "1"],
  [
    "The Thingamabob™",
    "Might",
    "5",
    null,
    "Crafted",
    "+1 Sneak +1 Wit +1 Manoeuvre while in Collection",
    "3",
    "3",
    "3",
    "3",
    "3",
  ],
  ["Rusty Nails", "Wit", "1", null, "Crafted", null, "0", "0", "0", "5", "0"],
  ["Leg-Powered Car", "Manoeuvre", "3", null, "Crafted", null, "0", "0", "2", "3", "0"],
  [
    "Glitter Bomb",
    "Wit",
    "2",
    null,
    "Crafted",
    "Enemy becomes disoriented, allowing them to become susceptible to Might",
    "0",
    "0",
    "1",
    "1",
    "1",
  ],
  ["Bow", "Might", "1", null, "Crafted", "Can be used on another players encounter.", "1", "0", "1", "0", "0"],
  ["Acme-Branded Anvil", "Might", "4", null, "Crafted", null, "0", "0", "1", "3", "0"],
  [
    "Megaphone",
    "Wit",
    "2",
    '"Call an enemy a slur"',
    "Crafted",
    "draws selected enemies towards you",
    "0",
    "0",
    "2",
    "1",
    "0",
  ],
  ["Special Key", null, null, null, "Crafted", "does nothing", "0", "0", "0", "2", "0"],
  [
    "Diamond Armor, Full Set",
    null,
    "0",
    "origin: the stash",
    "Crafted",
    "prevents loss encounter/event status. one time use",
    "0",
    "0",
    "0",
    "1",
    "2",
  ],
  [
    "Duct Taped Wings",
    "Manoeuvre",
    "4",
    '"Im basically flying now."',
    "Crafted",
    "can move 1 extra space next turn after use",
    "0",
    "0",
    "2",
    "3",
    "0",
  ],
  [
    "Overcomplicated Contraption",
    "Might",
    "5",
    '"Its held together with hopes and curses"',
    "Crafted",
    "Encounters you face have -1 score until you fail an encounter, at which point, destroy this scheme",
    "0",
    "0",
    "0",
    "5",
    "2",
  ],
  [
    "Decoy Goblin",
    "Deception",
    "3",
    "It's just a pile of rags with googly eyes…",
    "Crafted",
    "Can be used out of turn to remove an encounter on any adjacent tile, can use this during other players turns",
    "0",
    "0",
    "1",
    "2",
    "1",
  ],
  [
    "Shiny Distraction",
    "Sneak",
    "2",
    "No one can resist the shiny",
    "Crafted",
    "Encounter becomes susceptible to Sneak",
    "0",
    "0",
    "0",
    "2",
    "1",
  ],
];

const SPECIAL_SCHEMES = [
  [
    "Flee",
    null,
    null,
    "run away little goblin child",
    "Free",
    "Avoid an encounters fail condition, miss out on success condition",
    "0",
    "0",
    "0",
    "0",
    "0",
  ],
  // ["Slap", "Might", "1", null, "Free", null, "0", "0", "0", "0", "0"],
];

const REWARD_SCHEMES = [
  ["Charm", null, null, "oolala", "Random Reward", null, "0", "0", "0", "0", "0"],
  ["Well Placed Slap", "Might", "3", null, "Random Reward", null, "0", "0", "0", "0", "0"],
  ["Tunnel Painted On Wall", "Deception", "2", null, "Random Reward", null, "0", "0", "0", "0", "0"],
  ["Offensive Gesture", "Deception", "3", ">:3", "Random Reward", null, "0", "0", "0", "0", "0"],
  [
    "Hold In A Sneeze",
    "Sneak",
    "1",
    "You manage not to sneeze, but now you wish you had.",
    "Random Reward",
    null,
    "0",
    "0",
    "0",
    "0",
    "0",
  ],
  ["Doing The Worm", "Manoeuvre", "3", null, "Random Reward", null, "0", "0", "0", "0", "0"],
  ["Frying Pan", "Might", "2", "*loud metal banging noise*", "Random Reward", null, "0", "0", "0", "0", "0"],
  ["Cat O' Nine Tails Whip", "Might", "3", null, "Random Reward", null, "0", "0", "0", "0", "0"],
  [
    "Farting So Hard That You Blast Off",
    "Manoeuvre",
    "4",
    null,
    "Random Reward",
    "Blast off",
    "0",
    "0",
    "0",
    "0",
    "0",
  ],
  ["Poorly Performed Pirouette", "Manoeuvre", "2", "So graceful...", "Random Reward", null, "0", "0", "0", "0", "0"],
  ["Avoiding Eye Contact", "Sneak", "2", null, "Random Reward", null, "0", "0", "0", "0", "0"],
  ["Bite", "Might", "4", '"Don\'t ask what happened in 87"', "Random Reward", null, "0", "0", "0", "0", "0"],
  [
    "Filthy Glasses",
    "Deception",
    "3",
    "Makes anyone around you feel... uncomfortable.",
    "Reward",
    null,
    "0",
    "0",
    "0",
    "0",
    "0",
  ],
  ["Goblin Legal Threat ", "Wit", "3", "My cousin is a lawyer!", "Reward", null, "0", "0", "0", "0", "0"],
];

const EVENTS = [
  ["Disappearing Handkerchief Trick", "Enemy", "Test Event", "Wit, Deception, Sneak, Manoeuvre, Might", "3", "\"Darn...\" gain 1 supply and 1 scrap", "He shoots you, but its fine other than the headache and you dropping all your scrap, Discard all your scrap."]
]

const LANDMARKS = [["A cool-ass looking tree", "Landmark", "Damn thats a cool-ass looking tree", "Gain 2 sticks each time you land on the tile with this card"]]

const SCHEMES = [...CRAFTED_SCHEMES, ...SPECIAL_SCHEMES, ...REWARD_SCHEMES];

export { SCHEMES, CRAFTED_SCHEMES, SPECIAL_SCHEMES, REWARD_SCHEMES, EVENTS, LANDMARKS };
